vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        upload_image_candidats:
            uri_prefix: /images/candidats
            upload_destination: '%kernel.project_dir%/public/images/candidats'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        upload_image_recruiters:
            uri_prefix: /images/recruiters
            upload_destination: '%kernel.project_dir%/public/images/recruiters'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        upload_cv_candidats:
            uri_prefix: /images/cv
            upload_destination: '%kernel.project_dir%/public/images/cv'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer